run:
  concurrency: 4
  timeout: 10m
  issues-exit-code: 1
  tests: true
  build-tags:
    - e2e

output:
  format: line-number

linters-settings:
  depguard:
    include-go-root: true
    packages-with-error-message:
      - "io/ioutil": "ioutil is deprecated in Go 1.16"
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  gci:
    local-prefixes: github.com/alex1989hu/kubelet-serving-cert-approver
  goconst:
    min-len: 3
    min-occurrences: 3
  goheader:
    template-path: ./hack/LICENSE.header
  ifshort:
    max-decl-chars: 30
    max-decl-lines: 1
  makezero:
    always: true
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    allow-no-explanation: []
    require-explanation: false
    require-specific: true
  lll:
    line-length: 120
    tab-width: 1
  promlinter:
    strict: true
  unused:
    check-exported: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  thelper:
    test:
      first: true
      name: true
      begin: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - lll
    - makezero
    - megacheck
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wrapcheck
    - wsl
  disable:
    - exhaustivestruct
    - funlen
    - gochecknoinits
    - gocognit
    - gomodguard
    - rowserrcheck
    - sqlclosecheck
  disable-all: false
  fast: false

issues:
  max-per-linter: 0
  max-same: 0
  new: false
