codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 0.5%
        base: auto
        if_ci_failed: success
    patch: off

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
