name: e2e-test
on:
  push:
    branches:
    - "*"
  pull_request:
permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arrays:
          [
            {
              node: "v1.24.17",
              digest: "cdc9decabd92a947a82117e03ed26c4cde03753f42c3ff7ca56bab39b6ec5200",
            },
            {
              node: "v1.25.16",
              digest: "fedeb7ebef9794b3acbe656901f87231fb33381e0f586033ed18d2587bd9b73d",
            },
            {
              node: "v1.26.15",
              digest: "70c6ccbd3ed58116ad489691148e0437d390ae4349d6990b9aa3863b5c5cc508",
            },
            {
              node: "v1.27.16",
              digest: "9a08bfb799b90527eb58f0c3ac54252c3578d93758bae768e975f1bd7ba3bca0",
            },
            {
              node: "v1.28.15",
              digest: "af665d70820b816eb1384b9f715f608dca9c625014ebbfa59415dcf703860e93",
            },
            {
              node: "v1.29.14",
              digest: "e7858e6394f5e834802ce573ab340a0584d8314f909cb0717e14b57f2dd97257",
            },
            {
              node: "v1.30.13",
              digest: "cf819926d6f5ba996f7489fa18a38156f952f5dd172395da7d83f734190e95da",
            },
            {
              node: "v1.31.14",
              digest: "e360318c07a2bb22ced43884c6884208a82d3da24828c9f1329222dd517adc06",
            },
            {
              node: "v1.32.11",
              digest: "831a3aa45e399a20b3aef41d6d8572cc6ff07b1f76cac1242ce26be0ccf86402",
            },
            {
              node: "v1.33.12",
              digest: "c899edd3a9766ac69d5cccc9c8ee342e1920434a2d8eab0e02f461d36df96b41",
            },
            {
              node: "v1.34.8",
              digest: "e9f9fd553828988bcae9c852223fb99f83380f251722a9313aa99f370bde7bfd",
            },
            {
              node: "v1.35.5",
              digest: "397bcc4ab091b9632fb3639d5cf020943ca40e90fe7bcc38409738a4a0d056ee",
            },
        ]
        install-mode:
        - ha
        - standalone
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set up kubectl
      uses: azure/setup-kubectl@v5
      with:
        version: ${{ matrix.arrays.node }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4.1.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4.1.0
    - name: Build Container Image
      uses: docker/build-push-action@v7.2.0
      with:
        context: .
        file: ./Dockerfile
        load: true
        platforms: linux/amd64
        provenance: false
        push: false
        tags: ghcr.io/${{ github.repository }}:ci
    - name: Set up KinD
      id: kind
      uses: helm/kind-action@v1.14.0
      with:
        config: ./hack/e2e-kind-config.yaml
        node_image: docker.io/kindest/node@sha256:${{ matrix.arrays.digest }}
        version: "v0.32.0"
        cluster_name: kind
    - name: Wait for KiND readiness
      run: |
          kubectl --namespace kube-system wait --for=condition=ready pod -l tier=control-plane --timeout=300s
          kubectl get nodes -o wide
    - name: Load image on the nodes of the KinD
      run: |
          kind load docker-image ghcr.io/${{ github.repository }}:ci
    - name: Patch Install Manifests
      run: |
          sed -i -e 's@imagePullPolicy: Always@imagePullPolicy: IfNotPresent@g' ./deploy/${{ matrix.install-mode }}-install.yaml
          sed -i -e 's@image: .*@image: ghcr.io/${{ github.repository }}:ci@g' ./deploy/${{ matrix.install-mode }}-install.yaml
    - name: Deploy Application
      id: deployment
      run: |
        kubectl apply -f ./deploy/${{ matrix.install-mode }}-install.yaml
        count=0
        until [[ $(kubectl --namespace kubelet-serving-cert-approver get pod --selector app.kubernetes.io/name=kubelet-serving-cert-approver 2>/dev/null) ]]; do
          count=$((count + 1))
          if [[ "${count}" -eq "150" ]]; then
            echo 'Wait Timeout exceeded' >&3
            return 1
          fi
            sleep 2
        done
        kubectl --namespace kubelet-serving-cert-approver wait --for=condition=ready pod --selector app.kubernetes.io/name=kubelet-serving-cert-approver --timeout=300s
    - name: Get deployment failure logs
      if: ${{ failure() && steps.kind.outcome == 'success' && steps.deployment.outputs.exit_code != 0 }}
      run: |
        kubectl --namespace kubelet-serving-cert-approver get events
        kubectl --namespace kubelet-serving-cert-approver describe deployments kubelet-serving-cert-approver
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        cache: true
        go-version: 1.26.4
    - name: Test Approved Certificate Signing Requests
      run: go test -tags=e2e -v ./e2e
    - name: Get Application logs
      if: ${{ always() && steps.kind.outcome == 'success' }}
      run: |
        kubectl --namespace kubelet-serving-cert-approver logs --selector app.kubernetes.io/name=kubelet-serving-cert-approver --prefix
