name: snyk
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  schedule:
    - cron: '0 12 * * 6'
jobs:
  snyk:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Snyk Vulnerability Scanner
        uses: snyk/actions/golang@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=./snyk.sarif
      - name: Upload Snyk Scan Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./snyk.sarif
